### ISSUE TITLE
'Final Winner' for Tournament Should Detect Ties

### ISSUE THREAD

**Issue by hawkerm** [Mikeware/SpaceBattleArena#105]
Not sure what to do with ties, but should at least display the tied players in the bracket.

**Comment by SeattleScape** [comment]
You could move the players into the next game (assuming there is one) but have them scored separately from the others or you could break off the map into two different instances that are running a different game in each one, having two different games running at the same time side by side with the tied players in one game and the current round players in the other game. If its the last match of the bracket you could either run another round or do something else if time is of the essence.

**Comment by hawkerm** [comment]
@SeattleScape for the Wild Tournament there is a take_ties property to advanced the tied students together, but it's just if two are tied at the very end that I don't highlight them both, it just picks one based on whatever arbitrary order.

Lots of interesting ideas here though.  Last year, I did start to make the tournament infrastructure a bit more open to allow for alternate implementations.  I may work on it a bit more still to support the cross-school tournament we're doing this year, but not sure yet how far I'll get.
