### ISSUE TITLE
FindTheMiddle doesn't call world_create of Game so can't spawn entities

### ISSUE THREAD

**Issue by hawkerm** [Mikeware/SpaceBattleArena#110]
we override the method but don't call the base class...oops

**Comment by peterdur** [comment]
Assuming this issue prevents planets/stars/etc. from appearing when running the FindTheMiddle game, I just noticed this issue while prepping for a class later this week. Is anything else broken that would nudge us toward skipping this game? (More fun, obviously, with planets, but still a potentially useful exercise without)

**Comment by hawkerm** [comment]
Hey @peterdur, correct, I forgot to call the spawn manager which deals with loading in all the set options for plants and things.

I actually just uploaded a new pre-release build from my branch which has a fix for this [here](https://github.com/Mikeware/SpaceBattleArena/releases/tag/b1113).  It also has improvements to the client API when dealing with angles, orientation and points.  There are a couple of parameter type changes, but shouldn't be hard to update if you've already started using v1.1 the library in class.

It certainly does make a big visual difference to have the pretty items in the background!  Otherwise the game will still run fine, I was just using this for a work event I did Monday.

If you can't upgrade yet, you can also populate the world with the 'A' key on the server and just add things after launching the server.  It's certainly a good initial challenge to get students oriented with the system. ;)

**Comment by peterdur** [comment]
Thanks for the info! I'll try it out.

**Comment by jpverhaeghe** [comment]
I'm using the new version now, and it seems to be working well. I did find that if you try to start a tournament with find the middle basic game, it fails saying it can't find the midpoint.

**Comment by hawkerm** [comment]
Thanks @jpverhaeghe, I'm checking it out now.  I had just run a Find the Middle Tournament before the change, but would be surprised if it broke.

I just reprod the issue.  Investigating...

I plan to drop a updated build with at least some other bug fixes this weekend sometime, so please feel free to be able to plan on using Find the Middle in Tournament mode.

**Comment by jpverhaeghe** [comment]
Attached is the text rile with the server output. The first is a normal call with no errors, the second is a call with the tournament. The screen goes dark, then it just drops back to the command prompt.
[FTM_Error.txt](https://github.com/Mikeware/SpaceBattleArena/files/255357/FTM_Error.txt)

**Comment by wortzmanb** [comment]
This should be fixed in release https://github.com/Mikeware/SpaceBattleArena/tree/b1114.
