### ISSUE TITLE
Make Dragons Track the Ship Instead of the Point

### ISSUE THREAD

**Issue by hawkerm** [Mikeware/SpaceBattleArena#111]
Dragons can get trapped spinning in circles, think it's because they're having trouble getting to their target point.

Should just have the dragon track the object until it leaves its sight or disappears.

**Comment by wortzmanb** [comment]
Should add a parameter to configure dragon's minimum speed.

**Comment by hawkerm** [comment]
Might want to look into making Dragon not an Asteroid?

**Comment by hawkerm** [comment]
Added move_speed_min/max to Asteroid and Dragon to directly control their starting velocity vector length :)
