### ISSUE TITLE
Consider adding an "Enabled Commands" option

### ISSUE THREAD

**Issue by wortzmanb** [Mikeware/SpaceBattleArena#119]
In some cases, it might be easier to enumerate the commands that are allowed rather than the ones that are not. (For example, in the Find The Middle, when we basically only want Thrust, Brake, and Rotate.)  Would also avoid having to update configs when new commands are added.

**Comment by hawkerm** [comment]
This may be broken??? Need to investigate as tested, but wasn't working in practice.  Forgot to look at before making b1118.

**Comment by hawkerm** [comment]
Seems to be working ok according to tests I wrote, not sure what we were seeing with issues in class, maybe a typo? (I know that in general should be handled better for configs, vNext...)
