### ISSUE TITLE
Implement hard limit checks in constructors of command classes, rather than relying on server.

### ISSUE THREAD

**Issue by wortzmanb** [Mikeware/SpaceBattleArena#123]
Look at [WorldCommands.py](https://github.com/Mikeware/SpaceBattleArena/blob/master/SBA_Serv/World/WorldCommands.py) for current limits.

**Comment by hawkerm** [comment]
Let's look at catching InvocationTargetException in the call to getNextCommand from TextClient and rethrowing innererror to see if it provides more useful client-side error stacks.
