### ISSUE TITLE
Consider ramifications of warp location being calculated early

### ISSUE THREAD

**Issue by wortzmanb** [Mikeware/SpaceBattleArena#129]
Currently the warp destination is based on your original location, meaning if you're moving (especially if you enter a wormhole), your warp could not end up where you expect.  Is this what we want?

**Comment by hawkerm** [comment]
Oops, I misread the code this morning.  It stores a relative distance based on your orientation at the time of instantiation, so when your warp actually executes you're moving the proper distance specified or to a random location from your current position (it's just setup ahead of time, but not to a fixed point).
