### ISSUE TITLE
Asteroid spawning not respecting minimum

### ISSUE THREAD

**Issue by wortzmanb** [Mikeware/SpaceBattleArena#130]
Seems to be stuck at 4 rather than designated value.

**Comment by wortzmanb** [comment]
Had to change extension to .txt to make GitHub happy.

[basicgame_survivor.cfg.txt](https://github.com/Mikeware/SpaceBattleArena/files/282994/basicgame_survivor.cfg.txt)

**Comment by hawkerm** [comment]
Well... Dragons are 'Asteroids' so... it's doing what I told it, just not what we expect...
