### ISSUE TITLE
Server crashes running Bauble Hunt with a Basic ship

### ISSUE THREAD

**Issue by stutlerk** [Mikeware/SpaceBattleArena#143]
Log file attached.
[SBA_Serv2017-04-06_151027.txt](https://github.com/Mikeware/SpaceBattleArena/files/904067/SBA_Serv2017-04-06_151027.txt)

**Comment by hawkerm** [comment]
Think this was actually a different issue.  Also discovered by another.  BaubleHunt is broken! :(

I have a fix though.  I apparently had only tested BaubleHunt with auto_start disabled, when enabled (i.e. for practice) it tries to generate the world before a value has been initialized and crashes the game.  This prevents it from properly registering any ship connecting.

I'm going to check a few things, so I'll try and get a build with a fix out this weekend.  *In the meantime*, just change the [game's auto_start](http://mikeware.github.io/SpaceBattleArena/server/config.html#game) property to **false**, this should allow you to start and play the game by pressing space after Space Battle loads.

    [Game]
    auto_start = false
