### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by markasoftware** [Mikeware/SpaceBattleArena#148]
On multiple machines and multiple operating systems, the "players" are all getting 100% CPU load on one core. It absolutely kills battery life and can threaten usability on lower-end machines. I don't think it should be this high since the client isn't really doing anything but a simple game loop. Would be great if you could look into this. Thanks!

**Comment by hawkerm** [comment]
@markasoftware, could you provide some more details?  

What version of Space Battle are you using? 

What OS and Java versions are on the machines?

What game is the server setup to play?  What are the ships trying to do? Are they getting any error messages back?

What do the client and server logs look like, could you attach them?

**Comment by markasoftware** [comment]
This issue is occuring on find the middle and baubles, we haven't done any of the other game modes yet. I experienced the issue with Java 8 on both Arch Linux and macOS (not sure exactly which version of mac was being used). I'll post the client logs (don't have access to the server) in a few days, but no errors were printed to the console at least.

**Comment by hawkerm** [comment]
I'll pin this one on @wortzmanb, but I think I've got some improvements that should help you out.  They'll be pushed and a new build dropped shortly.  @markasoftware thanks for reporting and staying vigilant!

**Comment by markasoftware** [comment]
Thanks! I think I'll have some logs to send tomorrow. Let me know if there's any other diagnostic stuff I should check.

**Comment by markasoftware** [comment]
@hawkerm can you confirm that you experienced this issue before the fix?

**Comment by hawkerm** [comment]
@markasoftware Yup, I saw it on my own machine, we were just never looking at the task manager/cpu before on the client code to give it much thought.  So, I verified that it went from like 14% CPU on my box (pegging one of my eight cores) to like 0.1%... 👍 

![image](https://cloud.githubusercontent.com/assets/8959496/26039388/4e4049b4-38cf-11e7-886d-10f6aa0f3b9c.png)

So, the [new release 1.2.0.1126](https://github.com/Mikeware/SpaceBattleArena/releases/tag/v1.2.0.1126) should help you out a lot.  

**Thanks for catching this**; it was really just a minor [fix](https://github.com/Mikeware/SpaceBattleArena/commit/aad9dae0b79c05ccd08a876477cec7e2f28d7dbd) on our side.

**Comment by markasoftware** [comment]
Great, thanks.
