### ISSUE TITLE
Cannot get information of other ships?

### ISSUE THREAD

**Issue by NERDARES** [Mikeware/SpaceBattleArena#149]
Not sure if this is intentional or not, but after scanning with radar results, iterating through each object of type "Ship", if I were to print out the enemy ship by calling its toString method, I get a load of details on the enemy ship such as Heath, energy, speed - HOWEVER : They all report as 0 or null except for the position of the enemy ship. Was this intended or is there a mistake?

**Comment by hawkerm** [comment]
That all depends... What level of [radar](http://mikeware.github.io/SpaceBattleArena/client/java_doc/ihs/apcs/spacebattle/commands/RadarCommand.html) are you performing? 

Some radar levels don't return all properties of the objects, so they will be zero or null. If you're performing a level 3 or 5 radar, then they should be populated.  At level 1 though, they'll all be blank as you're only going to get the number of objects (via length of the results).

**Comment by NERDARES** [comment]
My bad, I just realized that only values like speed and direction come up at level 5. Guess I should pay attention with the documentation more >.<
