### ISSUE TITLE
Server Doesn't Always Terminate on Exit

### ISSUE THREAD

**Issue by hawkerm** [Mikeware/SpaceBattleArena#2]
Think this is only when run from source.  Think it's an extra thread in the networking side of things.  But it's been an annoyance.

**Comment by hawkerm** [comment]
Haven't seen this running from VS or from the EXE.  Maybe an issue running directly from python interpreter on command-line?

**Comment by hawkerm** [comment]
This this has to do with the timer used by Hungry Hungry Baubles and Bauble Hunt.  Will have to investigate more...

**Comment by hawkerm** [comment]
Think that was one issue, seems to work in the default case now, but network threads still hanging:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "atexit.pyo", line 24, in _run_exitfuncs
  File "Server\MWNL2.pyo", line 202, in __close
  File "Server\MWNL2.pyo", line 521, in close
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "atexit.pyo", line 24, in _run_exitfuncs
  File "Server\MWNL2.pyo", line 202, in __close
  File "Server\MWNL2.pyo", line 521, in close
KeyboardInterrupt

**Comment by hawkerm** [comment]
Looks like we're certainly getting stuck there on the thread, but if we try and forcibly flag the connection ending, we won't always send out our disconnect message to the clients to tell them to terminate... going to need to investigate more on this.

**Comment by hawkerm** [comment]
As part of #68, I started writing some more infrastructure for testing networked clients and just trying to understand this space better.  It certainly seems like our server is getting stuck when disconnecting.

In fact, I imagine that we're keeping every thread we open hung somewhere and that may be one main performance issue we see when start the year and students are continually disconnecting and connecting.

I've never given it a high priority, but it certainly is climbing it's way up.

**Comment by hawkerm** [comment]
Looks like I've solved an issue with leaving some threads behind when a client disconnects gracefully (was getting stuck in the command wait loop in the sever).

However, still might be an issue with closing all the connections when the server tries to shutdown.  Getting better though.

Gave all the threads names so it's a bit easier to diagnose.

**Comment by jpverhaeghe** [comment]
Where should I look for updates to the JAR and Server files for Java 7? Github?

Jim Verhaeghe

Computer Science Teacher

Ballard High School
