### ISSUE TITLE
Objects added after server starts do not respect configuration

### ISSUE THREAD

**Issue by wortzmanb** [Mikeware/SpaceBattleArena#70]
Nebulas and planets added after the server has started still have drag/gravity, even when drag/gravity has been disabled in the config file.

**Comment by hawkerm** [comment]
Right... for whatever reason I don't pass the config object to the GUI.  So, this is a bit more complicated as I should just pass it (vs. grabbing it from the game object reference...).  Anyway, I'll take a look later.

**Comment by hawkerm** [comment]
Related to #57.

**Comment by hawkerm** [comment]
Adding a SpawnManager for #83, so adding the helpers used for that to the GUI as well.

**Comment by hawkerm** [comment]
Resolved as part of adding Spawn Manager f07594603697038c1245083353308be2d9648929
