### ISSUE TITLE
Make getAngleTo and getOrientation use the same range of values

### ISSUE THREAD

**Issue by wortzmanb** [Mikeware/SpaceBattleArena#72]
getAngleTo is [-180, 180]
getOrientation is [0, 360]

**Comment by hawkerm** [comment]
Just a note, getOrientation is returning the value the Server provides, which we try to keep between 0 and 360 with the Rotate command, but it's not guaranteed that the physics engine stays in those bounds.

So, if you want to enforce this paradigm, you'll probably have to do the bounds check of the value in the method of the ObjectStatus class.

**Comment by wortzmanb** [comment]
Make everything work in the range [0, 360] by adding a % 360 to all of:
   ObjectStatus.getOrientation
   ObjectStatus.getMovementDirection
   Point.getAngleTo
